### ISSUE TITLE
aclocal version

### ISSUE THREAD

**Issue by B0P0H0K** [besm6/dispak#1]
The build process is bitching about not being able to find aclocal-1.11, because my aclocal is 1.13.
I am seeing, that aclocal-1.11 (the version part) is [semi]hardcoded in aclocal.m4.
Is this the intention and how can I straighten this out?

**Comment by sergev** [comment]
Need to update aclocal.m4. Try to run 'aclocal' - it should help.

**Comment by B0P0H0K** [comment]
Which one do I need to run first, aclocal or ./configure?
I also saw a similar warning regarding automake:

> WARNING: `automake-1.11' is missing on your system.

However, when I tried running automake, I got this:

> configure.ac:9: error: required file 'simh/Makefile.in' not found
> configure.ac:10: error: required file 'sbor/emd2simh/Makefile.in' not found

**Comment by B0P0H0K** [comment]
Note, that I have only extracted dispak:

> git clone https://github.com/besm6/dispak.git

I thought that would be sufficient for the dispak simulator.

**Comment by sergev** [comment]
Try now. I believe I had fixed it in https://github.com/besm6/dispak/commit/c8d756925f5f21ef9473c58d6d02c2bbb2343851

The only issue now is that disk images are not included.
I would propose to modify the makefile to build and install the dispak binary only, and create a separate script for installing disk images from besm6.github.io repository.

**Comment by B0P0H0K** [comment]
The build is still failing.
Attaching the log.
And there's a few warnings. I am planning to fix them, once my build is fixed.
[MAKE.txt](https://github.com/besm6/dispak/files/618471/MAKE.txt)

**Comment by sergev** [comment]
OK, disk images are now downloaded and installed on demand.
See https://github.com/besm6/dispak/commit/06dedfafec4c96486e8ac9d224d682b2de4fac90

**Comment by leobru** [comment]
The project has been converted to cmake.
